### ISSUE TITLE
Security Risk - push command adds db url from .kansorc to the design doc.

### ISSUE THREAD

**Issue by ozomer** [kanso/kanso#409]
[push.js line 124](https://github.com/kanso/kanso/blob/master/lib/commands/push.js#L124)

The design doc is created with a `kanso.config._url` field that contains the url from the `.kansorc` file.

Following the explanation [here](http://kan.so/docs/Configuration_.kansorc), it is recommended to put the username and password in the `.kansorc` file (and add it to `.gitignore`).

This will be very bad if your couchdb has public read access...

@ryanramage

**Comment by mandric** [comment]
This was fixed in 0.4.0.
