### ISSUE TITLE
kanso repository is down

### ISSUE THREAD

**Issue by squirrelpiles** [kanso/kanso#417]
Error: 503: Service Unavailable
    at Function.exports.statusCodeError (/usr/lib/node_modules/kanso/lib/couchdb.js:258:16)
    at ClientRequest.CouchDB.client (/usr/lib/node_modules/kanso/lib/couchdb.js:201:32)
    at ClientRequest.EventEmitter.emit (events.js:96:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1582:7)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
    at Socket.socketOnData [as ondata] (http.js:1485:20)
    at TCP.onread (net.js:404:27)
Failed

**Comment by caolan** [comment]
It should be back up now.

**Comment by mandric** [comment]
works for me.

**Comment by notatestuser** [comment]
it's down again

**Comment by browndav** [comment]
Hey @caolan, we're using Kanso in production and have quite a bit of EC2 capacity available. Is there something we can help with? It'd be pretty easy for us to run a Docker or LXC or AMI image, either as the primary repository or as a mirror (patch required, probably).Let me know. We're using it daily in CI, and would probably be able to monitor the machine pretty well.

**Comment by caolan** [comment]
Thanks David,

I'll get in touch and we can come up with a plan to move it over :) I think
the main problem is that the VM hosts some other services and it
occasionally get memory starved. On it's own machine it should be fairly
reliable.

**Comment by notatestuser** [comment]
and agaimn

**Comment by browndav** [comment]
Provisioning a new server today; I'll get in contact with Caolan in the mean time and get the machine back up.

**Comment by grimborg** [comment]
Any news on the mirror? Kanso seems to be down again.

**Comment by browndav** [comment]
We have 54.149.91.215 mostly built out; finishing a few setup / DNS transition details this week, and then we should be ready to switch over. Thanks for your patience; trying to squeeze this in to my schedule and not doing a spectacular job of it.

**Comment by Floby** [comment]
Hello,

Are there any news of this?

Couldn't kanso depend on an existing repository like npm.org ?

**Comment by mandric** [comment]
Ok give this a whirl http://kanso.app.medicmobile.org/ let me know if you find any issues.

**Comment by grimborg** [comment]
{"error": "render_error","reason": "function raised error: (new
ReferenceError(\"console is not defined\", \"events\", 172)) \nstacktrace:
(\"afterResponse\",g)@events:172\n(\"afterResponse\",(function (info, req,
res) {$(\"#topnav
li\").removeClass(\"active\");$(\"#home_nav_link\").addClass(\"active\");}))@events:210\n(null,[object
Object])@lib/shows:11\n((function (doc, req)
{events.once(\"afterResponse\", function (info, req, res) {$(\"#topnav
li\").removeClass(\"active\");$(\"#home_nav_link\").addClass(\"active\");});if
(req.client && utils.initial_hit) {} else {return {title: \"Kanso\",
content: templates.render(\"home.html\", req, {}), navpage:
\"home\"};}}),null,[object Object])@duality/core:729\n(null,[object
Object])@shows.home:1\nrunShow(function (doc, req) {var core =
require(\"duality/core\");var fn = require(\"lib/app\").shows.home;return
core.runShow(fn, doc, req);},[object Object],[object
Array])@/usr/share/couchdb/server/main.js:919\n(function (doc, req) {var
core = require(\"duality/core\");var fn =
require(\"lib/app\").shows.home;return core.runShow(fn, doc, req);},[object
Object],[object
Array])@/usr/share/couchdb/server/main.js:1029\n(\"_design/kanso_home\",[object
Array],[object
Array])@/usr/share/couchdb/server/main.js:1517\n()@/usr/share/couchdb/server/main.js:1562\n@
/usr/share/couchdb/server/main.js:1573\n"}

Òscar Vilaplana

2015-02-24 20:31 GMT+01:00 Milan Andric <notifications@github.com>:

**Comment by browndav** [comment]
DNS switchover for kan.so is in progress; the old TTL was about four hours, so there may be a substantial delay before the default repository address starts working again.

**Comment by mandric** [comment]
@grimborg I think this same bug might be on kan.so as well, and it's spurious, should go away on reload.

**Comment by grimborg** [comment]
It's great to see improvement in this area. Thanks for the effort!

**Comment by mandric** [comment]
Migration complete.

**Comment by browndav** [comment]
Thanks for your patience, everyone.
