### ISSUE TITLE
Node v0.12.x compatibility

### ISSUE THREAD

**Issue by Floby** [kanso/kanso#424]
It seems that Kanso cannot operate on node.js v0.12.

It first breaks on `/lib/utils.js` line 14 when requiring process.bindings('evals'). But I suspect there are other adaptations needed.

Are there any plans to support 0.12 ?

**Comment by garethbowen** [comment]
Hi @Floby. This is a duplicate of #422 and the PR #423. I (or someone else) will get on to this soon.

**Comment by garethbowen** [comment]
Closing as duplicate.
