### ISSUE TITLE
Kanso is down

### ISSUE THREAD

**Issue by mickaeltr** [kanso/kanso#430]
Hello,

It looks like Kanso is down.

```
kanso install            
installing from directory .
Building version tree...
checking properties
checking modules
Error: Error: connect ETIMEDOUT 109.68.33.64:80
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
Error: Error: connect ETIMEDOUT 109.68.33.64:80
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
Error: Error: socket hang up
    at createHangUpError (_http_client.js:239:15)
    at Socket.socketCloseListener (_http_client.js:271:23)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:477:12)
Error: Error: socket hang up
    at createHangUpError (_http_client.js:239:15)
    at Socket.socketCloseListener (_http_client.js:271:23)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:477:12)
Failed
```

```
curl -vvv http://kan.so/
*   Trying 109.68.33.64...
* connect to 109.68.33.64 port 80 failed: Operation timed out
* Failed to connect to kan.so port 80: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to kan.so port 80: Operation timed out
```

Thank you

**Comment by browndav** [comment]
Sorry for the delay. The author's DNS delegation appears to be misconfigured; the name should be pointing to 54.149.91.215. I've contacted the DNS maintainer and will try to get the issue fixed there upstream ASAP. In the mean time, you may be able to use /etc/hosts and that IP to remain productive until the issue is resolved.

Thanks, and sorry again for the downtime and the delay.

**Comment by browndav** [comment]
@caolan: You wouldn't be around and messing with DNS entries for some reason in the kan.so zonefile, would you?

**Comment by mickaeltr** [comment]
Thanks for the update and workaround.

**Comment by werty1st** [comment]
it seems to be down again. does somebody know how to mirror it?

**Comment by jmatsushita** [comment]
If someone is looking to see the website: http://54.149.91.215/home/_design/kanso_home/_rewrite/

**Comment by werty1st** [comment]
How can i use kanso install? Will the page stay offline?

**Comment by mickaeltr** [comment]
It should work if you add the following in your `/etc/hosts` file (or the equivalent in Windows):
```
54.149.91.215 kan.so
```

**Comment by werty1st** [comment]
I thought the dns Problem was fixed...

**Comment by mickaeltr** [comment]
@browndav & @caolan , do you have any update on this issue? Thank you

**Comment by werty1st** [comment]
i really like kanso but if its offline all the time i cant work with it any more. :(

can somebody recommend a good alternative couchapp tool?

i found [node.couchapp.js](https://github.com/mikeal/node.couchapp.js) and a [Python based Couchapp](https://github.com/couchapp/couchapp)

i will try node couchapp first.

**Comment by mickaeltr** [comment]
Kanso stopped working again, because the http://kan.so now redirects (301) to https://kanso.app.medicmobile.org/

The repository URL is hardcoded in the kanso package, however I manage to make it work again by creating a `.kansorc` file in my HOME directory, containing:

`exports.repositories = ["https://kanso.app.medicmobile.org/repository"];`

**Comment by mickaeltr** [comment]
I've created a pull-request which hopefully will resolve this Kanso availability issue: #432

**Comment by mickaeltr** [comment]
Thank you @mandric for merging my pull-request.
Any idea why the Travis job is failing for Node 0.12 https://travis-ci.org/kanso/kanso/jobs/158862826 ?

**Comment by mwillers** [comment]
@mandric is it possible to update kanso on npm? I am getting version 0.5.0 with the old repository URL. 
thanks! 👍

**Comment by proegssilb** [comment]
Bumped into the same issue. Since I'm on Windows, and %HOME% isn't defined on Windows, the config-file-in-home trick doesn't work. Instead, you can put a .kansorc file in your project directory, and that seems to work so far.

Still, it'd be good if we could update kanso on NPM.

**Comment by mandric** [comment]
Ok, pushed a 0.5.1 on npm!  Sorry about that.
